---
abstract: 'Fast C metadata and tag reader for all common audio file formats'
author:
  - 'Andy Grundman <andy@hybridized.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Audio-Scan
no_index:
  directory:
    - t
    - inc
requires:
  Test::Warn: '0'
version: '0.98'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
